name: Python_PLIB_Jasvinder_Hotfix_Project
description: ''
version: v1
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: pythonplibjasvinderhotfixproject
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-05-09 07:31:13'
pipelines:
  pipelines/Pipeline_1:
    name: Pipeline_1
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-09 07:31:13'
    datasets:
      inputs:
      - datasets/dataset_cust_in
      outputs:
      - datasets/dataset_out_13579
    subgraphs: []
    dependencies: {}
datasets:
  datasets/dataset_cust_in:
    name: dataset_cust_in
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2024-05-09 07:31:53'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2024-05-09 07:31:53'
  datasets/dataset_out_13579:
    name: dataset_out_13579
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2024-05-09 07:32:14'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2024-05-09 07:32:14'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-09 07:31:13'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-05-09T07:31:13.791573Z'
  name: plibMaven
  version: 7.1.95
  id: '1130350663'
  createdAt: '2024-05-09T07:31:13.791573Z'
  type: plibMaven
- modifiedAt: '2024-05-09T07:31:13.791573Z'
  name: plibPypi
  version: 1.8.15
  id: '226600657'
  createdAt: '2024-05-09T07:31:13.791573Z'
  type: plibPypi
projectDependencies:
  '5':
    projectUID: 5
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/cnXuekdF_team_5/cnXuekdF_project_5.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-05-09 07:31:00'
  '40':
    projectUID: 40
    projectName: ProphecySparkMachineLearningPython
    repositoryPath: gitUri=http://gitserver:3000/cnXuekdF_team_5/JkrhU1ZT_project_40.git&subPath=
    version: ProphecySparkMachineLearningPython/0.0.3
    isDefault: true
    author: null
    createdAt: '2024-05-09 07:31:00'
  '4':
    projectUID: 4
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/cnXuekdF_team_5/cnXuekdF_project_4.git&subPath=
    version: 0.2.12
    isDefault: true
    author: null
    createdAt: '2024-05-09 07:31:00'
  '6':
    projectUID: 6
    projectName: ProphecyStreamingPython
    repositoryPath: gitUri=http://gitserver:3000/cnXuekdF_team_5/cnXuekdF_project_6.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-05-09 07:31:00'
  '7':
    projectUID: 7
    projectName: ProphecyWebAppPython
    repositoryPath: gitUri=http://gitserver:3000/cnXuekdF_team_5/cnXuekdF_project_7.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-05-09 07:31:00'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
