name: HelloWorld
description: ''
version: v1
author: null
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2023-12-15 05:10:09'
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-12-15 05:10:09'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-12-15 05:10:09'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    subgraphs: []
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-12-15 05:10:10'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customer_totals
    subgraphs: []
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-12-15 05:10:10'
    datasets:
      inputs:
      - datasets/farmers-markets
      - datasets/irs-zipcode-data
      outputs:
      - datasets/farmers_market_tax_report
    subgraphs: []
    dependencies: {}
datasets:
  datasets/report:
    name: report
    description: Final report for the bank
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/customers:
    name: customers
    description: All the customers
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2023-12-15 05:10:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2023-12-15 05:10:09'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-12-15 05:10:09'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-06-20T06:55:27.959673Z'
  name: plibMaven
  version: 8.0.11
  id: '1202885043'
  createdAt: '2024-06-20T06:55:27.959627Z'
- type: plibPypi
  modifiedAt: '2024-06-20T06:55:27.959713Z'
  name: plibPypi
  version: 1.9.5
  id: '820350969'
  createdAt: '2024-06-20T06:55:27.959703Z'
projectDependencies:
  '4':
    projectUID: 4
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/cnXuekdF_team_5/cnXuekdF_project_4.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-06-20 06:56:11'
  '5':
    projectUID: 5
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/cnXuekdF_team_5/cnXuekdF_project_5.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-06-20 06:55:32'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
